#!/bin/bash
conda_env="anaconda3/bin/activate coding-learning-env"
repo_loc="git-chao-repos/coding-learning"
cd ~
source ${conda_env}
cd ${repo_loc}
conda env export > conda-env.yml
conda env export --no-builds > conda-no-builds-env.yml
conda env export --no-builds -f environment.yml
