name: coding-learning-env
channels:
  - defaults
dependencies:
  - alabaster=0.7.12
  - asn1crypto=0.24.0
  - astroid=2.2.5
  - babel=2.7.0
  - ca-certificates=2019.5.15
  - cairo=1.14.12
  - certifi=2019.6.16
  - cffi=1.12.3
  - chardet=3.0.4
  - cryptography=2.7
  - docutils=0.14
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - fribidi=1.0.5
  - gettext=0.19.8.1
  - glib=2.56.2
  - graphite2=1.3.13
  - graphviz=2.40.1
  - harfbuzz=1.8.8
  - icu=58.2
  - idna=2.8
  - imagesize=1.1.0
  - isort=4.3.21
  - jinja2=2.10.1
  - jpeg=9b
  - lazy-object-proxy=1.4.1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libiconv=1.15
  - libpng=1.6.37
  - libtiff=4.0.10
  - libxml2=2.9.9
  - markupsafe=1.1.1
  - mccabe=0.6.1
  - ncurses=6.1
  - openssl=1.1.1c
  - packaging=19.0
  - pango=1.42.4
  - pcre=8.43
  - pip=19.1.1
  - pixman=0.38.0
  - pycparser=2.19
  - pygments=2.4.2
  - pylint=2.3.1
  - pyopenssl=19.0.0
  - pyparsing=2.4.0
  - pysocks=1.7.0
  - python=3.6.8
  - python-graphviz=0.10.1
  - pytz=2019.1
  - readline=7.0
  - requests=2.22.0
  - setuptools=41.0.1
  - six=1.12.0
  - snowballstemmer=1.9.0
  - sphinx=2.1.2
  - sphinx_rtd_theme=0.4.3
  - sphinxcontrib-applehelp=1.0.1
  - sphinxcontrib-devhelp=1.0.1
  - sphinxcontrib-htmlhelp=1.0.2
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.2
  - sphinxcontrib-serializinghtml=1.1.3
  - sqlite=3.28.0
  - tk=8.6.8
  - typed-ast=1.3.4
  - urllib3=1.24.2
  - wheel=0.33.4
  - wrapt=1.11.2
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
